enable-magisk-update = true # set this to false if you do not want to receive updates for the module in magisk app
parallel-jobs = 1

# add 'enabled = false' for not patching a specific app or remove it from the config
# see https://github.com/j-hc/revanced-magisk-module/blob/main/CONFIG.md for more detailed explanations

# you can use rvmm-config-gen to generate a config

[Music]
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube-music/"
arch = "arm64-v8a"
included-patches = "'Amoled' 'Disable DRC audio' 'Spoof streaming data' 'Bitrate default value' 'Bypass image region restrictions' 'Certificate spoof' 'Change share sheet' 'Change start page' 'Custom branding icon for YouTube Music' 'Custom branding name for YouTube Music' 'Custom header for YouTube Music' 'Disable Cairo splash animation' 'Disable auto captions' 'Disable dislike redirection' 'Enable OPUS codec' 'Enable debug logging' 'Enable landscape mode' 'Flyout menu components' 'Hide account components' 'Hide action bar components' 'Hide ads' 'Hide layout components' 'Hide overlay filter' 'Hide player overlay filter' 'Navigation bar components' 'Player components' 'Remove background playback restrictions' 'Remove viewer discretion dialog' 'Restore old style library shelf' 'Return YouTube Dislike' 'Return YouTube Username' 'Sanitize sharing links' 'Settings for YouTube Music' 'SponsorBlock' 'Spoof app version' 'Spoof client' 'Translations for YouTube Music' 'Video playback' 'Visual preferences icons for YouTube Music'"
cli-source = "inotia00/revanced-cli"
patches-source = "inotia00/revanced-patches"
cli-version = "dev"
patches-version = "dev"
build-mode = "both"
